### ISSUE TITLE
Canvas implementation?

### ISSUE THREAD

**Issue by nonlinearcom** [vasturiano/d3-geo-zoom#1]
Hi Vasturiano, 

is it possible to integrate the zoom and pan behaviour into a canvas map?
Thanks in advance!

Manuel

**Comment by vasturiano** [comment]
@nonlinearcom the module is agnostic of the DOM element type. If a DOM element is supported by the underlying [d3-zoom](https://github.com/d3/d3-zoom), it should be supported in d3-geo-zoom.
