### ISSUE TITLE
Trying to keep the mouse over the same point while pan/zooming

### ISSUE THREAD

**Issue by antonytrupe** [vasturiano/d3-geo-zoom#12]
Maybe there's away to adjust speed or something, but its not jumping out at me. I'm poking through d3-zoom too. Any thoughts welcomed.

**Comment by antonytrupe** [comment]
I must be doing something funky somewhere, the examples in the project work like I want my stuff to work.

**Comment by vasturiano** [comment]
@antonytrupe if you can make a simple reproducing example on [codepen.io](codepen.io), I can look a little deeper to see where the culprit may be.

**Comment by antonytrupe** [comment]
I think it has something to do with having multiple contexts with zooming added to them, or at least the way I'm doing it.
https://codepen.io/tonytrupe/pen/jOqjGvE

**Comment by antonytrupe** [comment]
I think its the presence of more canvas elements, whether or not they have anything using them or not.

**Comment by antonytrupe** [comment]
Doesn't happen with geozoom:https://codepen.io/tonytrupe/pen/BaKXwXE

**Comment by antonytrupe** [comment]
It feels like something is getting confused about the mouse position when calculating how far the mouse has moved. There are no issues zooming. When multiple canvases are on the page, the 1st one doesn't have any issues, but the rest do.

**Comment by antonytrupe** [comment]
I took the canvas example from the project and made minor layout tweaks to it. https://codepen.io/tonytrupe/pen/oNxKrLq
It uses geoOrthographic instead of geoWinkel3, so gets less confused, but it still doesn't pan quite right when the canvas is offset from the window.

I think https://github.com/vasturiano/d3-geo-zoom/blob/master/src/geoZoom.js#L9 needs tweaked to make the mouse position relative to the canvas instead of the whole window, but I don't know how to do that.

**Comment by antonytrupe** [comment]
Pretty sure I figured it out, pull request submitted. Let me know if I missed something or style/name changes or whatever.

**Comment by vasturiano** [comment]
@antonytrupe with your PR merged, this issue should now be fixed. `v1.4.1` published. Let me know if you notice anything else unusual.
And thanks again for looking into it.
