### ISSUE TITLE
Error while importing d3GeoZoom as ES6 module

### ISSUE THREAD

**Issue by melalj** [vasturiano/d3-geo-zoom#5]
I followed your instructions to import the module with the ES6 syntax:
```js
import d3GeoZoom from 'd3-geo-zoom';
```

And I get this error:
```
TypeError: (0 , _d3GeoZoom2.default) is not a function
```

I tried with `import { d3GeoZoom } from 'd3-geo-zoom';` but no luck.

**Comment by vasturiano** [comment]
Thanks for the report @melalj! This is now fixed in `v1.2.1`. `import d3GeoZoom from 'd3-geo-zoom';` should now work.

It was wrongly exporting a named module (`geoZoom`) instead of using the default as described in the readme.
