### ISSUE TITLE
On mobile device example of library flickers a lot while zooming

### ISSUE THREAD

**Issue by stripathix** [vasturiano/d3-geo-zoom#8]
Can this be solved? Attached screen recording.

https://youtu.be/4yzn1tjV8G8

**Comment by stripathix** [comment]
I think this happen because while zoom panning gets distorted

**Comment by Fil** [comment]
Yes, the system is confused when we use two fingers touch — the reference point randomly jumps from one finger to the other.

I've started working on this issue already (https://observablehq.com/d/1ea380bf05fbf68c) but it's not perfect yet.

[EDIT] maybe it's perfect now :)

[EDIT2] still missing the "rotate" gesture

**Comment by vasturiano** [comment]
@fil nice! If I understand right, this seems related to how we extract pointer coordinates, currently done with [d3 mouse](https://github.com/d3/d3-selection#mouse), but that's not appropriate for 2+ finger touch interaction, thus causing the flicker.

Converting the detection into a hybrid of `touch`/`mouse` would possibly get it there. Was that your approach? I can try to PR this into the lib.

**Comment by stripathix** [comment]
@Fil  I would also suggest, especially for mobile devices call to render is always done through window.requestAnimationFrame(render). It improves the performance 10 times 🙂.

**Comment by Fil** [comment]
I have addressed all these problems in a new iteration of the notebook https://observablehq.com/d/7a912fba32fbe641

I don't see any difference when using window.requestAnimationFrame, maybe it's because I'm testing on a sufficiently fast device. Please have a look and tell me.

I plan to rework the notebook before publishing, but the code is already free to grab if you like.

One thing that is missing is the inertia. I really want to launch a rotation and see the marble spinning for a while, but the current system it makes it hard to stop at a precise rotation, so it also would need to be fixed.

**Comment by stripathix** [comment]
New improvements looks really cool 😍. 

@Fil actually I too see when running as a website it does not have any issue without RequestAnimationFrame on mobile device, but when we run it as a mobile hybrid application using Cordova or capacitor then It has huge lag. 
Maybe it's as per developer use case if he wants it.

**Comment by Fil** [comment]
OK—maybe it's enough if render is defined as :
`render: () => window.requestAnimationFrame(() => { actual drawing code })`

It's a bit verbose, but if we're sure it can be useful in some cases, it can be added as a standard operation.

**Comment by stripathix** [comment]
Hi @Fil in your https://observablehq.com/d/7a912fba32fbe641, I am trying to have the scale and rotate to geoJson bounds programmatically. It does works but when I pan or zoom back then the globe moves mack to default zoom.

To programmatically zoom to given geoJson bound I am doing this 

```
function zoomAndRotateToFitLineString() {
           var d = {
                "type": "Feature",
                "geometry": {
                    "type": "LineString",
                    "coordinates": lineStringPoints
                }
            };
            var p = d3.geoCentroid(d);
            var a = path.bounds(d)
            projection.rotate([-p[0], -p[1]])
              .fitExtent([[10, 10], [width, height]], d);
}
```
When page loads it nicely centers
  
![image](https://user-images.githubusercontent.com/8480351/79038943-3b4aff80-7bfb-11ea-8a47-5f8596265bd2.png)

But as soon as I do drag or zoom, the globe is back to zoomed out position. I am not sure why it preserves old scale even after using .fitExtent(). Am i missing something?

**Comment by Fil** [comment]
Do you apply the rotation before you create the map? If you do it after,
you should change not only the rotate, but at the same time change the
__zoom property on the map, accordingly.

**Comment by stripathix** [comment]
Thanks, @Fil  that did the trick :-). Just needed to add below call after fitExtent
```
            d3.select(ctx.canvas)
                .property("__zoom", d3.zoomIdentity.scale(projection.scale()))
```

**Comment by stripathix** [comment]
Hi, @Fil do we need to do __zoom property on the map when we apply zoom on Mercator projection too? 
My projection looks like 
```
projection = d3.geoMercator()
                .translate([width / 2, height / 2]);
```

And then in use fitExtent to get center and zoom to GeoJson object like
```
var geoJson = {
                "type": "Feature",
                "geometry": {
                    "type": "LineString",
                    "coordinates": lineStringPoints
                }
            };
projection.fitExtent([
                [10, 10],
                [width - 10, height - 10]
            ], geoJson);
d3.select(ctx.canvas)
            .property("__zoom", d3.zoomIdentity.translate(projection.translate()[1], projection.translate()[0]).scale(projection.scale()));
```

This does work fine but when I pan or zoom it goes somewhere else.

I think something is not right when setting __zoom property :-(

**Comment by Fil** [comment]
Guessing from chunks of code is a lot of work. Please share a complete code, preferably as a block or observable notebook.

**Comment by stripathix** [comment]
Created a block.

https://bl.ocks.org/stripathix/7ae230609a8997a1dd64111aa144daa4

Initially, you will see a black screen but if you do pan or zoom action then you will see the map. This happens because of a function zoomToGeoJson. Wanted to get map zoomed to provided LineString geojson


```
function zoomToGeoJson() {
  var geoJson = {
    "type": "FeatureCollection",
    "features": [{
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -471.35742187499994,
            44.276671273775186
          ],
          [
            -462.919921875,
            37.50972584293751
          ],
          [
            -451.14257812499994,
            38.54816542304656
          ]
        ]
      }
    }]
  };
  projection.fitSize([
    [10, 10],
    [width - 10, height - 10]
  ], geoJson);
  
  d3.select(canvas)
    .property("__zoom", d3.zoomIdentity.scale(projection.scale()));
}
```

**Comment by Fil** [comment]
Here's a version that works. You can compare to see the 2 or 3 things that needed a modification
https://bl.ocks.org/Fil/6a768c90c4ccba298cf1dd950cfd529a
